### ISSUE TITLE
Add multiple goals to dashboard

### ISSUE THREAD

**Issue by mbfisher** [write-track/prolifiko.com#1]
We need to be able to show multiple goals on the dashboard. It should look something like:

# Current goal
- Just the name and target date - click to show description
- If there's no active step, a CTA to create one
- CTA to complete the goal

## Current step
- Name and deadline
- Description

## Past steps
- Just the name
- Greyed out?
- Show the deadline?
- Click to expand

# Past goals
- Same as past steps

**Comment by dan-j** [comment]
Just pushed a new branch feature/dashboard-multiple-goals with some initial work.

**Comment by dan-j** [comment]
Next steps are to create multiple goals using django admin page since the business logic doesn't yet support creating multiple goals. Once that's done, need to test that the page I've pushed works, and probably make UI tweaks (but not too much). 

If it's a quick win, I'll look at adding "time remaining" into the current goal block.

**Comment by dan-j** [comment]
![image](https://cloud.githubusercontent.com/assets/5727701/19619937/e9d0c7ac-9869-11e6-8069-537f3ba71c8c.png)

**Comment by dan-j** [comment]
Multiple goals with completed steps greyed, need to mark the 5-day challenge as complete.

**Comment by dan-j** [comment]
![image](https://cloud.githubusercontent.com/assets/5727701/19620297/505c4bd8-9872-11e6-9eef-cae845470d14.png)

**Comment by dan-j** [comment]
I think the dashboard should only show "active" stuff and if you need to see "completed" stuff, to click the goal in question to go to the /goals/:id page.. thoughts?

Having access to completed stuff here in a collapsable menu seems pointless since you're likely not going to want it in the dashboard. 

I think we need to do some proper UX work to design how it should look since this isn't my forte

**Comment by dan-j** [comment]
No active goal - CTA Create Goal
Active Step - CTA track progress
No Active step - CTA create step or complete goal (existing URL somewhere)

**Comment by dan-j** [comment]
See commit comment above to view screenshots :)

**Comment by dan-j** [comment]
FYI: just amended a commit to remove comments so browsing to the commit via the commits page means the comment with screenshots aren't there, you'll need to click the above link to get there.. won't do that again haha

**Comment by dan-j** [comment]
This should not be completed, will attach video demo if I can get it < 10MB :)
