### ISSUE TITLE
Update goal completion

### ISSUE THREAD

**Issue by mbfisher** [write-track/prolifiko.com#4]
- Five day challenges should auto complete when the fifth step is completed
- Goals should prompt when a step is completed and on the dashboard
- Five day challenge complete to take you to subscription
- Goal complete should take you to new goal

**Comment by dan-j** [comment]
Not sure I understand the second point? Although I'm also not sure how much time I'll get before you're back so may not be worth explaining. Will focus on the issue already assigned to me first.

**Comment by mbfisher** [comment]
When you're in the 5 day challenge and complete a step you get sent straight to creating new step. When you're in a custom step you need to be able to complete the goal rather than create a new step. This is probably a bit blurred with #2.

M

**Comment by dan-j** [comment]
The logic is now correct except there's a bug if you try to create a 6th step. 

`steps/new.html` is rendered with the property of 

```
        'next_step_nth': goal.next_step_nth,
```

This throws an exception because it looks up a word representing 1st 2nd... 5th etc. When it gets to '6' there's no element in the array. Surely there's a library so we don't have to do this ourselves? Will look into it tomorrow.
